### ISSUE TITLE
generate fr and de - 674

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/cloud-volumes-ontap-991-relnotes#18]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
German build failed, restarted. French okay.

**Comment by ntap-bmegan** [comment]
Rebuild successful.

**Comment by netapp-gudugunti** [comment]
Site is up and running.
Total TOT: 7 minutes.
